language: cpp
install:
  - source ci/travis_prepare.sh
script:
- cmake .
- cmake --build ./packages/work1/
- cmake --build ./packages/work1/ --target test
- cmake --build ./packages/work1/ --target package
deploy:
  provider: script
  skip_cleanup: true
  script: