language: cpp
dist: xenial
install:
- source ci/travis_prepare.sh
script:
- cmake .
- cmake --build ./packages/work1/
- cmake --build ./packages/work1/ --target test
- cmake --build ./packages/work1/ --target package
deploy:
  provider: bintray
  skip_cleanup: true
  file: bintray/description.json 
  user: wamonk
  key: $BINTRAY_API_KEY
   # secure: O65B5UhVR79x9CFGOyzODrEwDMY9/AWMGjD7VVoboYB+4YdZoKiqPtN76i1rHmvRUU5+fXnTFaG5zsMhgRkLIE/eXULLwTo8B9rDSplNposOCbp6pxfRjejQF7PPG/Le6PmcbA6VFzmFNsBmGkAx3H0xWl2afTekTzkNc/LaNC3aLl62mXa7MYACnPxNveyuCrMMSMizpGShY/iZsLW6dSnki+OpagtiCKosHsoPFVzjL+8m+o0hCvzYE23po6zcuuW2gnlwsz2WcBwx8C3JXlA1nsGY+bYuIQsJ5LS8MXPX8yJ+ambxP8mDZJPGeaNDNt/bS9J9+70d90OWY1fJoUa8IgqLKDAvckB2yfZwN5L4+WJT3mT5AqTGReLBnh8L2aHm13BMJ/4t4EIwoweVv2ZalIetX1UDo+UiXGG3699vOZml04muLHv95drFQtDpXl8/1YlBSJV3apmJThzBQ24gv4wNTizn5d8SzY7RMUOAvEvSzs+a7cILOj/gJD03libhK3MIa0D+eBwmis5sN/rwA9BrBV8u12+aic+VZ6UEKK9OhEtFNkoAVQAPxIrED8IyOlfbkdyIIUx+tj3OgVg11UkrnTmzxdIhk+15p9CoTWGcrJKI1fQuzYm0PMS7uxz8mYPQIHesajGUAVVmyw1hGwBoGU8GJzNN5ml/wZw=
